### PR TITLE
Frontend - Introduce redux

### PR DESCRIPTION
**Pull request by josephj**
The front-end architecture is getting complicated, especially for the QuarterView component. It's better to bring in the Redux for maintainability reason.

**Why**
Props delegation is difficult
https://speakerdeck.com/josephj/lets-redux

**How**
https://medium.com/@notrab/getting-started-with-create-react-app-redux-react-router-redux-thunk-d6a19259f71f

**Implementation Highlight**
1. [store.js - Create Store](https://github.com/efcsydney/efcsydney-roster/pull/72/files#diff-36c47fb33022d2183169ad7c05522fad)
1. [root index.js - Connect Store and Route](https://github.com/efcsydney/efcsydney-roster/pull/72/files#diff-c3ede5b5250ec9a7181630da3090839a)
1. [redux.js - Define Actions and Reducer](https://github.com/efcsydney/efcsydney-roster/pull/72/files#diff-87acf66fda2986380f837e3c3ea52bd6)
1. [NavBar - Connect and update store from a component](https://github.com/efcsydney/efcsydney-roster/pull/72/files#diff-261a113f2f200d2ab89a201889f1c8a4)

### CODE REVIEW

**Comment by josephj** [comment]
[(1) FE Improve - Introducing Redux [0]](https://trello.com/c/qxJWN71b/150-1-fe-improve-introducing-redux-0)

**Comment by josephj** [comment]
Hey @DumDumGeniuss,

Thanks man! It's a nice feedback. 

It's quite interesting after I checked the react-redux-universal-hot-example architecture you provided. The duck pattern wants us to combine the reducers and the action creators since they are almost always a pair. 

> however 95% of the time, it's only one reducer/actions pair that ever needs their associated actions.

Do you find it's a totally different philosophy for the react-redux-universal-hot-example container components? **The container component, for 95% of the the time, it's only belonging to one module**.  Why should we separate them? 

This guy provides a very good explanation why should we do that. ( https://jaysoo.ca/2016/02/28/organizing-redux-application/ ) I really love this idea. 

```
todos/
  components/
  actions.js
  actionTypes.js
  constants.js
  index.js
  reducer.js
index.js
rootReducer.js
```

Let me know how you feel. :)

**Comment by DumDumGeniuss** [comment]
Hello @josephj 
It's a really good point, actually [React-Boilerplate](https://github.com/react-boilerplate/react-boilerplate) use the same idea for Redux.
Make every part  as independent as possible is always the good thing to do.
One of the pros is you can focus on certain part and it's easy to debug and change.
And one of the cons is if different containers use exactly same action, we might to think about either sharing the action or building it again.

Both of them are good choice, and I think your idea fit this project, then just use your one 😄 
(And maybe we can remove Modules and do everything in Containers like [React-Boilerplate](https://github.com/react-boilerplate/react-boilerplate)  do, same idea but makes more sense)

**Comment by josephj** [comment]
@DumDumGeniuss 

Thanks man!

You are right. I feel react-redux-universal-hot-example is more for small project or tool but the react-boilerplate is more for the real world project. You can't easily avoid to have duplicate actions when project gets more and more complicated. 

The way we overcome this is to have a tool called **entity** in our company. It can generate sets of reducers, actions, and epics for different reusable data entity. You can choose to connect to this global data entity or your local store.

**Store**
```
{
  entity: { // Global entities which is reusable
    users: {
      // Normalized data with normalizr    
    }
  },
  'welcome/index': { // Local data which is container specific
    data: [],
    meta: {}
  }
}
```

**Actions**

It will generate the sets of actions with the consistent naming convention.

* `requestRetrieveUsers` -> Ask to fetch data 
* `receiveRetrieveIdUsers` -> Data fetched with responsed data from server
* `requestModifyIdUsers` -> Ask to modify a specific item
* `receiveModifyIdUsers` -> Item modified with responsed data from server
* and more...

So that you can subscribe this actions in your local reducer.

**Comment by yhua045** [comment]
[(3) API - error logging [3]](https://trello.com/c/hT59kzzf/128-3-api-error-logging-3)

**Pull request merged**
