### PR TITLE
Bugfix frontend last row missing

### PR DESCRIPTION
**Pull request by jeffreyxuan**
@josephj  more space at bottom

### CODE REVIEW

**Comment by josephj** [comment]
@jeffreyxuan 

It works good on my desktop browsers, but fails on my phone and simulator. Maybe we can add the margin on the parent (App) level?

[iphone-margin-bottom.png](https://trello-attachments.s3.amazonaws.com/59f05d916a0b6a501a5e96fe/5a1933d06cfb65e2661cddd3/55f9530cc6c14ccf463eeb0950408524/iphone-margin-bottom.png)

**Comment by jeffreyxuan** [comment]
How about this? Add bottom padding in Wrapper instead

**Comment by josephj** [comment]
[(0.5) Mobile UI Bug - Last row is invisible [0.5]](https://trello.com/c/VXMgDm6Y/85-05-mobile-ui-bug-last-row-is-invisible-05)

**Comment by josephj** [comment]
All working good! 👍

**Pull request merged**
