### PR TITLE
#423 Admin Navigation enhancement and better mobile view

### PR DESCRIPTION
**Pull request by josephj**
#### Changelog

* Update the Admin Navigation
* Making the Admin Layout and refactoring the`<Route/>` 
* Responsive Enhancement
   * Making scrollable Table 
   * Vertical form label and control

image
image
image

#### QA URL

https://demo-roster.efcsydney.org/#/admin

#### Note

Our original plan is to have Users, the Email and Changelog are what I want to achieve. I will remove it if it's not doable. 

#### Acceptance Criteria

- [ ] Ensure the page is switched correctly while user clicks the navigation item
- [ ] Ensure the url is updated correspondly while user clicks the navigation item
- [ ] Ensure the mobile view is better than before

### CODE REVIEW

**Comment by josephj** [comment]
@neochen04 
It will be nice if you can try to understand the change I made after your work.
https://github.com/efcsydney/efcsydney-roster/pull/424/files#diff-32c11a72ee6dc974212847a43bca218a

@trust2065 
I made some changes for admin layout which can reduce duplication when you start the user management page. Please help to have a look.

**Comment by trust2065** [comment]
@josephj  Thanks for doing my job hahaha... I like the way you move the route from `app.js` to `module/admin`.
On the mobile navigator, what do you think to make it fixed on top?

**Comment by trust2065** [comment]
Unable to drag the screen on navigator on mobile, you think `max-width: 100%` work?
image

**Comment by neochen04** [comment]
@josephj  Appreciate the changes XD. I can roughly understand that you used the 'table' tag for this part. Am i correct? However, I have no idea what the scripts about

{_.map(
                      data,
                      ({ frequency, label, id, positions, name }) => (
                        <Row key={id}>

Are they part of Javascript or another programming language?

**Comment by trust2065** [comment]
@neochen04 
It's javascript, you can have a look at [lodash map](https://lodash.com/docs/4.17.10#map)

**Comment by josephj** [comment]
@trust2065 

I can try to update the navigation to make it fit with the screen.  Making the nav to be fixed on the top is a good idea. We can implement it in the next sprint. 

@neochen04 

We use `map` to convert one array to another array. What you mentioned actually is actually involved with some ES6 syntax sugar. 

Say if we have the following data, but we only need name strings in an array.
```js
const data = [{name: 'Neo', role: 'Speaker}, {name: 'Choco', role: 'PA/PPT'}];
```

You can use a stupid way.
```js
var newData = []
data.forEach(function (item) {
  newData.push(item.name); 
}); 
console.log(newData) // output ['Neo', 'Choco']
```
Or use `map` with ES6 syntax sugar. The following 3 ways are all identical.
```js
data = data.map(function (item) {
  return item.name
});  // output ['Neo', 'Choco']

data = data.map((item) =>  item.name);  // output ['Neo', 'Choco']

data = data.map(({ name }) => name);  // output ['Neo', 'Choco']
```

**Comment by josephj** [comment]
@trust2065 

I've fixed the cropping issue. Please have another look.
image

**Comment by neochen04** [comment]
@josephj  @trust2065  Got it! Thank you for your explanations.

**Pull request merged**
