### PR TITLE
#233 Quarter View - Render views w/ service frequency

### PR DESCRIPTION
**Pull request by josephj**
#### Description

Ability to render Quarter View by the Service frequency setting, instead of the backend data. 

#### QA URL

https://demo-roster.efcsydney.org/#/chinese
https://demo-roster.efcsydney.org/#/engish
https://demo-roster.efcsydney.org/#/preschool-junior
https://demo-roster.efcsydney.org/#/preschool-middle
https://demo-roster.efcsydney.org/#/preschool-middle
https://demo-roster.efcsydney.org/#/preschool-senior

#### Acceptance Criteria

- [ ] Ensure the view renders correctly according to the frequency
- [ ] Ensure you can save a day which already has one or more positions (names) specified. 
- [ ] Ensure you can save a day which doesn't have any positions (names) specified.

### CODE REVIEW

**Comment by josephj** [comment]
@james1239090 

The main changes happen in this commit. https://github.com/efcsydney/efcsydney-roster/pull/319/commits/8d709be4e19f99e7fdf4fb45335a65d0acb02ebe Can you help to review the code? 

@yhua045 

Can you help to review the functionality?

**Comment by yhua045** [comment]
@josephj , 

There seemed to be a bug during the switch of the service (the selected value of the service drop down list is changed). The bug is that the application seem to lose the event ID (see image attached). I am still trying to figure out the steps to reproduce and will update this PR once I managed to reproduce it consistently.

image

**Comment by yhua045** [comment]
@josephj ,

If it is too difficult to fix from the front end (I assume the logic in the front end is getting more and more complex), I am happy to change the logic of the API so you don't need to supply the ID and the API will use the service name and date to determine if a serviceInfo already exists and insert/update accordingly

**Comment by yhua045** [comment]
@josephj ,

Not sure if this is the same issue, but it looks like the app is trying to call PUT api/serviceInfo/{id} without include the id.

image

**Comment by josephj** [comment]
@yhua045 

It seems still failing after I removed the `id` prop. I have also changed to use `POST /api/serviceInfo` for non-existed dates. Also not working for me. Can you help to have a look?

**Pull request merged**
