### PR TITLE
#305: Include event ID in the event entity when events API returns th…

### PR DESCRIPTION
**Pull request by yhua045**
#### Description

Ensure the event ID is included in every Event entity when Events API builds the response.

#### QA URL

https://demo-roster.efcsydney.org/api/events?from=2017-10-08&to=2017-10-15&category=english

#### Acceptance Criteria

- [ ] Ensure that ID is always contained in each member of the 'members' property

### CODE REVIEW

**Comment by josephj** [comment]
@yhua045 

I can't see the id exist?

image

**Comment by yhua045** [comment]
No, that's serviceInfo ID. Which ID are you looking for? the ServiceInfo ID or Event ID? The event is under 'members' property (see below)

image

**Comment by josephj** [comment]
@yhua045 

Assigning this pull request back to you. Can you also make sure the qa will be rollbacked?

**Comment by yhua045** [comment]
Rolled back all changes and smoke tested QA environment

**Pull request closed without merging**
