### PR TITLE
#266: Create service API to enable service creation

### PR DESCRIPTION
**Pull request by yhua045**
#### Description
Create a new Service API to enable new service creation. 

The new end point is POST api/services

The sample data is listed below:

PLEASE NOTE: if the 'id' is supplied, it will 'Update' the service rather than 'Create'.

{
  "name": "special-service2",
  "locale": "zh-TW",
  "label": "Special Service 2",
  "footnoteLabel": "Visit",
  "frequency": {"name": "Saturday"},
  "positions": [
    {"name": "Position 1", "order": "1"},
    {"name": "Position 2", "order": "2"}
  ]
}

#### QA URL

Use Postman

#### Acceptance Criteria

- [x] Ensure the returned API response contains 'id' field for the newly created service and position

### CODE REVIEW

**Comment by josephj** [comment]
Hi @yhua045,

It works as expected. Just not sure about the following part. 

```
frequency: {
  name: "Saturday"
}
```
Will it be `{"frequency": "Saturday"}` on the master?

Is this because of #196 ? I think we have to revert #196 on QA branch. 
image

Can you help to revert that just on tje qa branch?

**Comment by josephj** [comment]
Besides, can you help to connect this pull request to #266 ?

**Comment by yhua045** [comment]
Absolutely, this pull request has been linked.

**Comment by josephj** [comment]
@yhua045 

All good. Please remember to merge it back to master so that @waguei-andrea can start to work on API integration.

**Pull request merged**
